### ISSUE TITLE
Use compressed (gzip) fasta and gtf

### ISSUE THREAD

**Issue by zeehio** [nf-core/scrnaseq#314] opened 2024-04-02 16:44 UTC
### Description of feature

It would be nice if the scrnaseq pipeline had a similar/compatible genome preparation as the rnaseq pipeline.

I guess we all lack the time to port and implement it avoiding deduplication.

See:

https://github.com/nf-core/rnaseq/blob/master/subworkflows/local/prepare_genome/main.nf

**Comment by grst** [comment] 2024-04-02 17:32
Duplicate of #313

**Comment by grst** [comment] 2024-04-02 17:32
Yeah, we should have this here... Do you want to make a PR?

**Closed by grst** 2024-04-02 17:32 UTC
Labels: enhancement

**Comment by grst** [comment] 2024-04-04 14:10
It's actually already implemented in #276. Will be fixed once this gets merged.
