### ISSUE TITLE
pyroe failed to return succesfully ExitStatus(unix_wait_status(256))

### ISSUE THREAD

**Issue by lfperales** [nf-core/scrnaseq#191] opened 2022-12-21 16:57 UTC
### Description of the bug

I'm running scrna using nextflow tower, and I get this error. It can be related with this https://github.com/nf-core/scrnaseq/issues/152#issue-1397792463

<img width="1201" alt="Screen Shot 2022-12-21 at 11 41 18 AM" src="https://user-images.githubusercontent.com/112426849/208961198-9e99e9c5-1fd4-43a8-878e-28e42d11b249.png">

**Comment by rob-p** [comment] 2023-01-19 19:06
Hi @lfperales,

  I'm happy to do what I can to help out with this, but I'm not entirely familiar with how I can/should test this out.  The issue seems (perhaps?) to be related to a missing command line parameter that was added to `pyroe` some time back.  Is the tower instance using the latest versions of all of the relevant tools?  How can I easily reproduce this behavior to test and try to fix it?

Thanks,
Rob

**Comment by lfperales** [comment] 2023-01-19 20:54
hello Rob, I don't know if tower is using the latest versions of all the tools? How can I do this? thank you

**Comment by drpatelh** [comment] 2023-01-19 23:25
We definitely need more information to help here @lfperales . Are you able to share the `.nextflow.log` file which you can download from Tower?

**Comment by lfperales** [comment] 2023-01-23 15:22
THIS IS THE COMPLETE LOG FROM BATCH

Downloading plugin nf-amazon@1.11.3
--
N E X T F L O W  ~  version 22.10.5
Pulling nf-core/scrnaseq ...
downloaded from https://github.com/nf-core/scrnaseq.git
Launching `https://github.com/nf-core/scrnaseq` [lethal_pesquet] DSL2 - revision: c86646e4a8 [2.1.0]
-[2m----------------------------------------------------[0m-
[0;32m,--.[0;30m/[0;32m,-.[0m
[0;34m        ___     __   __   __   ___     [0;32m/,-._.--~'[0m
[0;34m  \|\ \| \|__  __ /  ` /  \ \|__) \|__         [0;33m}  {[0m
[0;34m  \| \\| \|       \__, \__/ \|  \ \|___     [0;32m\`-._,-`-,[0m
[0;32m`._,._,'[0m
[0;35m  nf-core/scrnaseq v2.1.0[0m
-[2m----------------------------------------------------[0m-
[1mCore Nextflow options[0m
[0;34mrevision        : [0;32m2.1.0[0m
[0;34mrunName         : [0;32mlethal_pesquet[0m
[0;34mlaunchDir       : [0;32m/[0m
[0;34mworkDir         : [0;32m/fsx[0m
[0;34mprojectDir      : [0;32m/.nextflow/assets/nf-core/scrnaseq[0m
[0;34muserName        : [0;32mroot[0m
[0;34mprofile         : [0;32mstandard[0m
[0;34mconfigFiles     : [0;32m/.nextflow/assets/nf-core/scrnaseq/nextflow.config, /nextflow.config[0m
[1mInput/output options[0m
[0;34minput           : [0;32mhttps://api.tower.nf/workspaces/166189419503828/datasets/4j9Fv2PcnYwVxh3SKXE6Gu/v/1/n/nash_ramachandran_one.csv[0m
[0;34moutdir          : [0;32ms3://pioneeringmedicines-data/Public/sc-RNAseq/nash/test_scrna/[0m
[1mMandatory arguments[0m
[0;34mprotocol        : [0;32m10XV3[0m
[1mReference genome options[0m
[0;34mgenome          : [0;32mGRCh38[0m
[0;34mfasta           : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa[0m
[0;34mgtf             : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Annotation/Genes/genes.gtf[0m
[1mKallisto/BUS Options[0m
[0;34mbustools_correct: [0;32mtrue[0m
!! Only displaying parameters that differ from the pipeline defaults !!
-[2m----------------------------------------------------[0m-
If you use nf-core/scrnaseq for your analysis please cite:
* The pipeline
https://doi.org/10.5281/zenodo.3568187
* The nf-core framework
https://doi.org/10.1038/s41587-020-0439-x
* Software dependencies
https://github.com/nf-core/scrnaseq/blob/master/CITATIONS.md
-[2m----------------------------------------------------[0m-
Monitor the execution with Nextflow Tower using this URL: https://tower.nf/orgs/FSP_Labs/workspaces/Pioneering_Medicines/watch/2TFXgnzzulzuGm
[78/f9c7f2] Submitted process > NFCORE_SCRNASEQ:SCRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (nash_ramachandran_one.csv)
Staging foreign file: s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa
Staging foreign file: s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Annotation/Genes/genes.gtf
[2e/af98c8] Submitted process > NFCORE_SCRNASEQ:SCRNASEQ:GTF_GENE_FILTER (genome.fa)
Staging foreign file: s3://pioneeringmedicines-data/public/scrna/nash/wang/raw/SRR10009435/cirrhotic1_cd45+_R1_001.fastq.gz
Staging foreign file: s3://pioneeringmedicines-data/public/scrna/nash/wang/raw/SRR10009435/cirrhotic1_cd45+_R2_001.fastq.gz
Staging foreign file: s3://pioneeringmedicines-data/public/scrna/nash/wang/raw/SRR10009436/cirrhotic1_cd45-A_R1_001.fastq.gz
Staging foreign file: s3://pioneeringmedicines-data/public/scrna/nash/wang/raw/SRR10009436/cirrhotic1_cd45-A_R2_001.fastq.gz
Staging foreign file: s3://pioneeringmedicines-data/public/scrna/nash/wang/raw/SRR10009437/cirrhotic1_cd45-B_R1_001.fastq.gz
Staging foreign file: s3://pioneeringmedicines-data/public/scrna/nash/wang/raw/SRR10009437/cirrhotic1_cd45-B_R2_001.fastq.gz
[c7/c5b7c4] Submitted process > NFCORE_SCRNASEQ:SCRNASEQ:SCRNASEQ_ALEVIN:SIMPLEAF_INDEX (genome_genes.gtf)
Error executing process > 'NFCORE_SCRNASEQ:SCRNASEQ:SCRNASEQ_ALEVIN:SIMPLEAF_INDEX (genome_genes.gtf)'
Caused by:
Essential container in task exited
Command executed:
# export required var
export ALEVIN_FRY_HOME=.
 
# prep simpleaf
simpleaf set-paths
 
# run simpleaf index
simpleaf \
index \
--threads 6 \
--fasta genome.fa \
--gtf genome_genes.gtf \
--rlen 91 \
-o salmon
 
cat <<-END_VERSIONS > versions.yml
"NFCORE_SCRNASEQ:SCRNASEQ:SCRNASEQ_ALEVIN:SIMPLEAF_INDEX":
simpleaf: $(simpleaf -V \| tr -d '\n' \| cut -d ' ' -f 2)
salmon: $(salmon --version \| sed -e "s/salmon //g")
END_VERSIONS
Command exit status:
1
Command output:
found `salmon` in the PATH at /usr/local/bin/salmon
found `alevin-fry` in the PATH at /usr/local/bin/alevin-fry
found `pyroe` in the PATH at /usr/local/bin/pyroe
Command error:
found `salmon` in the PATH at /usr/local/bin/salmon
found `alevin-fry` in the PATH at /usr/local/bin/alevin-fry
found `pyroe` in the PATH at /usr/local/bin/pyroe
Error: pyroe failed to return succesfully ExitStatus(unix_wait_status(256))
Work dir:
/fsx/c7/c5b7c4ce31c52974aec26822e1ce96
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Execution cancelled -- Finishing pending tasks before exit
-[0;35m[nf-core/scrnaseq][0;31m Pipeline completed with errors[0m-
Waiting for file transfers to complete (6 files)
Waiting for file transfers to complete (4 files)
Waiting for file transfers to complete (3 files)
Waiting for file transfers to complete (1 files)
Saving cache: .nextflow/cache/98017613-1fc7-428d-8cbe-1fbd32410a22 => /fsx/.nextflow/cache/98017613-1fc7-428d-8cbe-1fbd32410a22


<br class="Apple-interchange-newline">

**Comment by lfperales** [comment] 2023-01-23 16:27
@drpatelh and @rob-p this is the complete log. Thank you for your help!

**Comment by rob-p** [comment] 2023-01-23 16:38
It looks to me like this is a version of pyroe so old that it doesn't even support the version flag `-V`.  How is the execution environment defined here (i.e. the versions of programs installed etc.).  The easiest thing to do would typically be to upgrade to the latest version if pyroe.  It is available both via pip and via bioconda.

**Comment by rob-p** [comment] 2023-01-23 18:38
@drpatelh — I think this question is more for you! I am not aware of what the update/upgrade policy is on tower. I've only used it in the past to monitor jobs that were launched and run locally where I had control of the execution environment.  If this is running on aws, then I would imagine the relevant images just need to bump the versions of these tools.

**Comment by drpatelh** [comment] 2023-01-23 19:03
Tower just pulls the pipeline from GitHub source and runs using the versions of the containers defined for that particular version of the pipeline (unless they are overridden by a config). So it shouldn't be doing anything special. Would need to investigate this further using the specific parameters used and possible replicating the settings used to create the Compute Environment.

**Comment by rob-p** [comment] 2023-01-23 19:27
So maybe these lines are an issue?

https://github.com/nf-core/scrnaseq/blob/c86646e4a818397f4bddfffd641b34240423f3ea/modules/local/simpleaf_index.nf#L5

https://github.com/nf-core/scrnaseq/blob/c86646e4a818397f4bddfffd641b34240423f3ea/modules/local/simpleaf_quant.nf#L5

They pull in a specific `simpleaf` from bioconda, which I presume is itself using older versions of pyroe / alevin-fry / salmon?

**Comment by drpatelh** [comment] 2023-01-23 19:43
Possibly. Nextflow will use the Docker container defined in the `container` definition below on AWSBatch:
https://github.com/nf-core/scrnaseq/blob/c86646e4a818397f4bddfffd641b34240423f3ea/modules/local/simpleaf_index.nf#L8

Quick test would be to pull that image and check the versions in the container. Clocked off for the day otherwise I would have done a quick test.

**Comment by maxulysse** [comment] 2023-01-24 08:13
```
docker run quay.io/biocontainers/simpleaf:0.5.2--h9f5acd7_0 pyroe -v
pyroe 0.6.2
```

**Comment by lfperales** [comment] 2023-01-24 20:27
is that the right version? @rob-p

**Comment by rob-p** [comment] 2023-01-24 21:24
Hi @lfperales, This version of simpleaf is rather old. The current version is [0.8.1](https://bioconda.github.io/recipes/simpleaf/README.html).  Without the ability to easily reproduce the problem (i.e. without a tower setup) I can't say if the update would fix it, but that's certainly the first thing to try.

**Comment by drpatelh** [comment] 2023-02-02 18:04
We have reproduced the issue on Tower (AWS Batch) and the pipeline fails with the same error even when using v0.8.1 of simpleaf. We are looking into it now and will try to reproduce locally.

**Comment by rob-p** [comment] 2023-02-02 20:10
Interesting!  Please keep me posted. I'm happy to help out however I can.

**Comment by robsyme** [comment] 2023-02-03 03:31
Pulling this apart was hampered a little by simpleaf's reluctance to share with us the stderr/stdout from the failing pyroe process. I've [created an issue here](https://github.com/COMBINE-lab/simpleaf/issues/43) and will try to submit a quick PR to address it over the weekend.

This was not a deal-breaker to understanding the bug, but it would have been a nice-to-have.

If we pull out the pyroe command from the simpleaf source code and run it in isolation:
```shell
pyroe make-splici genome.fa genome_genes.gtf 91 salmon/ref
```
We see that it is trying to call `gene_id` on a pyranges object that has no such attribute:
```
  File "/usr/local/bin/pyroe", line 195, in <module>
    make_splici_txome(
  File "/usr/local/lib/python3.10/site-packages/pyroe/make_splici_txome.py", line 265, in make_splici_txome
    introns.Name = introns.gene_id
  File "/usr/local/lib/python3.10/site-packages/pyranges/pyranges.py", line 269, in __getattr__
    return _getattr(self, name)
  File "/usr/local/lib/python3.10/site-packages/pyranges/methods/attr.py", line 67, in _getattr
    raise AttributeError("PyRanges object has no attribute", name)
AttributeError: ('PyRanges object has no attribute', 'gene_id')
```

If we look at the [relevant regions](https://github.com/COMBINE-lab/pyroe/blob/6bbda459b73444c05beff84aeaccb31cb3edf8cc/src/pyroe/make_splici_txome.py#L414-L429) in `make_splici_txome.py`:
```python
# Read the GTF into a pyranges object
gr = pr.read_gtf(gtf_path)

# get introns
introns = gr.features.introns(by="transcript")
introns.Name = introns.gene_id
```

We see that it reads the gtf into a pyranges object `gr`, but the `gr.features` method relies on "transcript" features in the GTF ([pyranges docs here](https://pyranges.readthedocs.io/en/latest/autoapi/pyranges/genomicfeatures/index.html#module-pyranges.genomicfeatures)).

The GTF loaded by the test_full profile `s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Annotation/Genes/genes.gtf`does not have any `transcript` features:

```
❯ aws s3 cp s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Annotation/Genes/genes.gtf .
❯ awk '$3 == "transcript"' genes.gtf
❯ 
```

... which means that `gr.features` returns an empty genomic features object, which does not have a `gene_id` object.

This can be fixed by passing the gtf through something like `gffread` which will add the features back in. I think that it would be sensible for `pyroe` to warn the user if no transcript features were detected (they are not officially part of the GTF spec), but I'll also add in a gffread process to the scrnaseq pipeline to fix the issue silently.

**Comment by robsyme** [comment] 2023-02-03 03:48
I have a branch [gtf-fixing](https://github.com/nf-core/scrnaseq/tree/gtf-fixing) where I'm running tests on the fix overnight. Will update here tomorrow.

**Comment by rob-p** [comment] 2023-02-03 04:49
Thanks for digging into this @robsyme!  I'm tagging @DongzeHe here as well (the main developer of `pyroe`).  For the reasons you state above, I also believe it would be reasonable to have `pyroe` act differently if only gene records and no transcript records are present — perhaps treat the gene annotation itself as a single transcript?  However, it's worth getting @DongzeHe's read on this.

**Comment by DongzeHE** [comment] 2023-02-03 17:05
This is a tricky question. Our _spliced+intronic_ reference relies on the annotation of transcripts. If this doesn't exist, how can we extract the (expanded) transcriptome from the gene annotations and the genome build? I mean, if there are no "transcripts" annotations, we cannot even extract the spliced transcripts from them, right? Did I misunderstand the problem?

**Comment by rob-p** [comment] 2023-02-03 18:31
From @robsyme's comment:

> This can be fixed by passing the gtf through something like gffread which will add the features back in. I think that it would be sensible for pyroe to warn the user if no transcript features were detected (they are not officially part of the GTF spec)

I agree that in this case, we could just return an error code and an informative message that e.g. it doesn't make sense to attempt to build a _spliced+intronic_ or _spliced+unspliced_ transcriptome given that no transcripts are annotated in the GTF.

**Comment by DongzeHE** [comment] 2023-02-04 03:54
Hi @robsyme, @lfperales  and @maxulysse, 

So we decided to make pyroe a little smarter to deal with missing transcript annotations, the rows in a GTF that defines the transcripts' range, or say bounds. 

We did think about some margin cases. For example, some but not all transcripts have their range defined in the GTF, or the transcript bounds defined in the GTF differ from those generated by their exons.

Notice that when generating the reference, if it finds anything inappropriate, for example, the `gene_name` or `gene_id` metadata field is missing, pyroe writes a clean GTF file with imputed values, such as imputing gene names using gene id.

Therefore, we proposed to do the followings. The overall idea is if we find anything inappropriate, then we fix them in the clean GTF file, but still use the annotations in the original bounds to extract introns if we can.

First, we check the `transcript_id` metadata field in the input GTF file. If it is missing, we just give up and report an error.

Then, we check if there are transcript annotations (the rows defining transcripts' range). 
- If there is no transcript annotation, we give a warning, get transcripts' bounds manually using their exons' bounds, write those bounds to the clean gtf file, and use them as the transcript ranges to extract introns. 
- If some of them are missing, we report a warning and impute the missing annotations in the clean GTF file, but still use the "transcript" rows in the original GTF file to extract introns. We will say in the error message that if the users want to use the annotations we generated, they should rerun pyroe using the clean GTF file.
- If the bounds defined in the "transcript" rows and those found manually (using exons' bounds) are different, we report a warning and use manually defined transcript annotations (from their exons' bounds) in the clean GTF file, but still extract introns using the transcripts' annotation in the original GTF file. We will say in the error message that if the users want to use the annotations we generated, they should rerun pyroe using the clean GTF file.

As we are not very familiar with the GTF files people used in practice, f there are other marginal cases we did not consider, please let us know! Thanks!


Best,
Dongze

**Comment by robsyme** [comment] 2023-02-04 21:07
That sounds like a perfectly reasonable plan. For testing, the iGenomes gtf for GRCh38 would be a good candidate:

```
s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Annotation/Genes/genes.gtf
```

Are you planning on joining exons into transcripts by the `transcript_id` attribute? Am I right in assuming that the bounds of the exons that share a `transcript_id` should be equal to the start+end of the (missing) transcript feature?

**Comment by DongzeHE** [comment] 2023-02-05 15:27
Hi @robsyme,

You are right. We plan to join only exons features. The reason is that although there are other feature types, for example, CDSs and UTRs, their intervals are always contained within some exon features. If this is not a universal rule, please let us know!

**Comment by robsyme** [comment] 2023-02-05 18:40
The universe of GTF/GFF interpretation is vast, but I think that your plan of taking the exons will catch almost all sane annotation sets. Thanks again!

**Comment by DongzeHE** [comment] 2023-02-06 21:19
Hi @robsyme,

I have made the changes and am now testing it. However, I found that the iGenomes gtf for GRCh38 you shared contains the gene annotation in some "special" chromosomes. That is, chromosomes that are not in the genome FASTA file. For example, 'chr1_GL383518v1_alt'.  If possible, could you please share the link to the genome FASTA file that matches the iGenomes GTF you shared?   

The genome build I used was downloaded from 

```
s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/
```

Best,
Dongze

**Comment by robsyme** [comment] 2023-02-07 01:38
Ah, this looks to be iGenomes being an unreliable resource (which is why nf-core is considering moving away from these datasets).

I'd recommend filtering the gtf. Something like

```bash
aws s3 cp s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa .
samtools faidx genome.fa
grep -f <(awk '{printf("^%s\\t\n", $1)}' genome.fa.fai) genes.gtf > genes.filtered.gtf
```

**Comment by rob-p** [comment] 2023-02-15 13:33
Hi @robsyme,

  All of our changes to pyroe and simpleaf have now been upstreamed. Is it worth pulling in the latest versions and seeing if this is resolved?

**Comment by robsyme** [comment] 2023-02-15 13:38
Yup, thanks for the prompt Rob. I'll pull them in today.

**Comment by grst** [comment] 2023-02-21 12:27
Closed by https://github.com/nf-core/scrnaseq/pull/198

**Closed by grst** 2023-02-21 12:27 UTC
Labels: bug
