### ISSUE TITLE
SMART-Seq2 support

### ISSUE THREAD

**Issue by heylf** [nf-core/scrnaseq#124] opened 2022-06-30 08:37 UTC
### Description of feature

I want to adapt the pipeline for SMART-Seq2 as well. There exist a SMART-seq2 nf-core pipeline (https://github.com/nf-core/smartseq2), but it is outdated and the last commit was 2 years ago. Do you think it is better two have two separate pipelines (10x / SMART), or would it be fine to merge them all together?

**Comment by grst** [comment] 2022-06-30 15:45
Hi @heylf, 

the smartseq2 pipeline was retired, because smartseq2 data can be analyzed just fine with the `rnaseq` pipeline. You probably just want so set some options to make it faster (e.g. skip a few QC steps, consider using pseudoalignment only, etc.) 

If you are interested in the Tracer/Bracer steps of the smartseq2 pipeline, there was at some point the plan to integrate them into the `airrflow` workflow I think, but that didn't happen so far. 

Best, 
Gregor

**Comment by grst** [comment] 2022-06-30 15:46
See also the discussion in the (archived) smartseq2 channel on slack: 
https://app.slack.com/client/TE6CZUZPH/CTKL84AQ6/thread/CTKL84AQ6-1611562336.007900?cdn_fallback=1

**Comment by heylf** [comment] 2022-06-30 17:22
Thank you @grst I am kind new to the nextflow community and will work more closely with the nf-core from now on, so I miss here and there some connections.

**Comment by grst** [comment] 2022-07-01 11:31
Closing this as it's not a bug or feature request of the scrnaseq pipeline. 
Please join us on slack if you have any questions how to run smartseq2 data with the rnaseq workflow!

**Closed by grst** 2022-07-01 11:31 UTC
Labels: enhancement
